modLoader="javafml"
loaderVersion="[39,)"
license="GPL3"

[[mods]]
modId="tac"
version="0.2.0"
displayName="Timeless and Classics"
updateJSONURL=""
displayURL=""
authors="Timeless Development Tema"
description='''
'''

[[dependencies.tac]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tac]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"